import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/ui/app-sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Encryptor } Decryptor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
            <main className="flex flex-col">
                <div className="flex flex-row items-center justify-center">
                  <SidebarTrigger className="w-10 h-10 m-5"/>
                  <h5 className="text-md lg:text-2xl font-bold">Encryption and Decryption Processes</h5>
                </div>
              {children}~
            </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
